item {
	id: 1
	name: 'apple'
}
item {
	id: 2
	name: 'orange'
}
item {
	id: 3
	name: 'coin'
}
item {
	id: 4
	name: 'chicken curry'
}
item {
	id: 5
	name: 'coca cola can'
}
item {
	id: 6
	name: 'fanta can'
}
item {
	id: 7
	name: 'ETA sour cream'
}
item {
	id: 8
	name: 'bluebird sour cream'
}
item {
	id: 9
	name: 'ETA chicken'
}
item {
	id: 10
	name: 'McDonalds fries'
}
item {
	id: 11
	name: 'McDonalds big-mac'
}
item {
	id: 12
	name: 'McDonalds mcchicken'
}
item {
	id: 13
	name: 'McDonalds filet-o-fish'
}
item {
	id: 14
	name: 'PizzaHut pizza'
}