export const LOAD_IMAGE_RESULT = 'LOAD_IMAGE_RESULT';
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const IMAGE_RESULT_FAILED = 'IMAGE_RESULT_FAILED';
export const CLEAR_IMAGE_RESULT = 'CLEAR_IMAGE_RESULT';